---

- name: "hallo_welt | Report: hallo_welt"
  ansible.builtin.command:
    cmd: "echo 'hallo welt'"
  register: ansible_cmdb_report_tmp_hallo_welt_cmd
  when: ansible_cmdb_report_hallo_welt
  ignore_errors: true
  changed_when: false

- name: "hallo_welt | Report: hallo_welt out"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_hallo_welt:
      - hallo_welt: "{{ ansible_cmdb_report_tmp_hallo_welt_cmd.stdout }}"
  when:
    - ansible_cmdb_report_hallo_welt
    - ansible_cmdb_report_tmp_hallo_welt_cmd.stdout is defined

- name: "hallo_welt | Report: hallo_welt out (unreachable)"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_hallo_welt:
      - hallo_welt: "unreachable"
  when:
    - ansible_cmdb_report_hallo_welt
    - ansible_cmdb_report_tmp_hallo_welt_cmd.stdout is not defined

- name: "hallo_welt | Report: hallo_welt out"
  ansible.builtin.set_fact:
    ansible_cmdb_report_output_hallo_welt:
      - hallo_welt: "{{ ansible_cmdb_report_tmp_hallo_welt }}"
  when: ansible_cmdb_report_hallo_welt
