---
- name: "hostvars | Report: hostvars"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_hostvars:
      - ansible_host: "{{ ansible_host | default('-not set-') }}"
        inventory_hostname: "{{ inventory_hostname }}"
        stage: "{{ stage | default('-not set-') }}"
        schedule: "{{ schedule | default('-not set-') }}"
        group: "{{ group | default('-not set-') }}"
        env: "{{ env | default('-not set-') }}"
        host_collection: "{{ host_collection | default('-not set-') }}"
        environment: "{{ hostvars[inventory_hostname]['environment'] | default('-not set-') }}"
        department: "{{ department | default('-not set-') }}"
        os: "{{ os | default('-not set-') }}"
        contact: "{{ contact | default('-not set-') }}"
  when: ansible_cmdb_report_hostvars
  register: ansible_cmdb_report_task_hostvars
  ignore_errors: true

- name: "hostvars | Report: hostvars (unreachable)"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_hostvars:
      - ansible_host: "{{ hostvars[iventory_hostname]['ansible_host'] | default('-not set-') }}"
        inventory_hostname: "{{ inventory_hostname }}"
        stage: "{{ stage | default('-not set-') }}"
        schedule: "{{ schedule | default('-not set-') }}"
        group: "{{ group | default('-not set-') }}"
        env: "{{ env | default('-not set-') }}"
        host_collection: "{{ host_collection | default('-not set-') }}"
        environment: "{{ hostvars[inventory_hostname]['environment'] | default('-not set-') }}"
        department: "{{ department | default('-not set-') }}"
        os: "{{ os | default('-not set-') }}"
        contact: "{{ contact | default('-not set-') }}"
  when:
    - ansible_cmdb_report_hostvars
    - ansible_cmdb_report_task_hostvars.failed

- name: "hostvars | Report: hostvars out"
  ansible.builtin.set_fact:
    ansible_cmdb_report_output_hostvars:
      - hostvars: "{{ ansible_cmdb_report_tmp_hostvars }}"
  when: ansible_cmdb_report_hostvars
