---

- name: "maxauthtries | Report: maxauthtries"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      sshd -T | grep -i tries | sed 's/maxauthtries //g'
    executable: /bin/bash
  register: ansible_cmdb_report_tmp_maxauthtries_cmd
  when: ansible_cmdb_report_maxauthtries
  ignore_errors: true
  changed_when: false

- name: "maxauthtries | Report: maxauthtries out"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_maxauthtries:
      - maxauthtries: "{{ ansible_cmdb_report_tmp_maxauthtries_cmd.stdout }}"
  when:
    - ansible_cmdb_report_maxauthtries
    - ansible_cmdb_report_tmp_maxauthtries_cmd.stdout is defined

- name: "maxauthtries | Report: maxauthtries out (unreachable)"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_maxauthtries:
      - maxauthtries: "unreachable"
  when:
    - ansible_cmdb_report_maxauthtries
    - ansible_cmdb_report_tmp_maxauthtries_cmd.stdout is not defined

- name: "maxauthtries | Report: maxauthtries out"
  ansible.builtin.set_fact:
    ansible_cmdb_report_output_maxauthtries:
      - maxauthtries: "{{ ansible_cmdb_report_tmp_maxauthtries }}"
  when: ansible_cmdb_report_maxauthtries
