---
- name: "sysinfo | Report: sysinfo"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_sysinfo:
      - inventory_hostname: "{{ inventory_hostname }}"
        hostname: "{{ ansible_facts.hostname }}"
        ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        load: "{{ ansible_facts.loadavg }}"
        distribution: "{{ ansible_facts.distribution }}"
        distribution_icon: "{{ ansible_facts.distribution | lower | regex_replace(' ', '') }}"
        os_family: "{{ ansible_facts.os_family }}"
        major_release: "{{ ansible_facts.distribution_major_version }}"
        processor_cores: "{{ ansible_facts.processor_cores }}"
        memory: "{{ ansible_facts.memtotal_mb }}"
        interfaces: "{{ ansible_facts.interfaces }}"
        virtualization: "{{ ansible_virtualization_role | default('n/a') }}"
        # facts: "{{ ansible_facts }}"
  when: ansible_cmdb_report_sysinfo
  register: ansible_cmdb_report_task_sysinfo
  ignore_errors: true

- name: "sysinfo | Report: sysinfo (unreachable)"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_sysinfo:
      - inventory_hostname: "{{ inventory_hostname }}"
        hostname: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        load: "unreachable"
        distribution: "unreachable"
        distribution_icon: "unreachable"
        os_family: "unreachable"
        major_release: "unreachable"
        processor_cores: "unreachable"
        memory: "unreachable"
        interfaces: "unreachable"
        virtualization: "unreachable"
        # facts: "{{ ansible_facts }}"
  when:
    - ansible_cmdb_report_sysinfo
    - ansible_cmdb_report_task_sysinfo.failed

- name: "sysinfo | Report: sysinfo out"
  ansible.builtin.set_fact:
    ansible_cmdb_report_output_sysinfo:
      - sysinfo: "{{ ansible_cmdb_report_tmp_sysinfo }}"
  when: ansible_cmdb_report_sysinfo
