---

- name: "uname | Report: uname"
  ansible.builtin.command:
    cmd: "uname -a"
  register: ansible_cmdb_report_tmp_uname_cmd
  when: ansible_cmdb_report_uname
  ignore_errors: true
  changed_when: false

- name: "uname | Report: uname out"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_uname:
      - uname: "{{ ansible_cmdb_report_tmp_uname_cmd.stdout }}"
        kernel_version: "{{ ansible_kernel }}"
  when:
    - ansible_cmdb_report_uname
    - ansible_cmdb_report_tmp_uname_cmd.stdout is defined

- name: "uname | Report: uname out (unreachable)"
  ansible.builtin.set_fact:
    ansible_cmdb_report_tmp_uname:
      - uname: "unreachable"
        kernel_version: "unreachable"
  when:
    - ansible_cmdb_report_uname
    - ansible_cmdb_report_tmp_uname_cmd.stdout is not defined

- name: "uname | Report: uname out"
  ansible.builtin.set_fact:
    ansible_cmdb_report_output_uname:
      - uname: "{{ ansible_cmdb_report_tmp_uname }}"
  when: ansible_cmdb_report_uname
